### PR TITLE
Fix version file, package import on wheel-based installation (e.g. with `pip install .`)

### PR DESCRIPTION
**Pull request by StanczakDominik**
This solves two problems from https://github.com/fsciortino/Aurora/issues/8 :

1. the version file is now attached to the source package via
   package_data. This is achieved through a rather ugly hack - I just
   `recursive-include`d the whole `aurora` directory. I couldn't come to
   terms with numpy's distutils.setup, which didn't want to let me
   include single files into wheels (but `sdist` works fine, which is
   confusing), so I sidestepped the issue. The directory is small, so
   the size (~300kb) should not be a problem - but I'd welcome a better
   solution!
    * I also changed setup.py to refer to the version in the source
      directory;
    * and `__init__.py` now finds it robustly, no matter the location,
      through pkgutil.
    * I was then able to remove `.version` from the main package
      directory, to decrease the confusion.
    * I also took the liberty to rename it to `version` (no starting
      dot), so Linux doesn't treat it as a hidden file.
2. I was getting a "no extension named `aurora._aurora`" error on
   importing the package; so I changed the extension's name from
   `_aurora` to `aurora._aurora`. It didn't break anything I was able to
   test; but it stopped `_aurora` from popping up as an independent
   package, which is a boon in my eyes.

### CODE REVIEW

**Review by fsciortino — APPROVED** [review]
This looks great! Thank you very much  :)

**Comment by fsciortino** [comment]
@StanczakDominik it seems that the current version works well with `pip install -e .`, but I'm still having issues installing from PyPI. The `version` file is not copied into the installation and, as a result, the code crashes with I try to `import aurora`...

Also, I pushed to master a clearer listing of requirements, but this isn't working quite right because packages like `omfit_eqdsk` and `omfit_gapy` are not on Anaconda, but they are available via PyPI. Conda does not seem to figure that out by itself.... so one needs to install those before installing `aurorafusion`, otherwise the `aurorafusion` installation will crash...

@StanczakDominik if you have any further thoughts on how to correct these issues, they would be very welcome!

**Comment by StanczakDominik** [comment]
I take it we're talking about https://test.pypi.org/project/aurorafusion/1.0.11/ ?  It is weird that the `version` file doesn't appear there. If I understand correctly, you just did `python setup.py sdist` and uploaded the .tar.gz that gets built, right? Admittedly I just focused on the wheel build, which might have been risky.

I'll tinker with it some more tomorrow and we'll get to the bottom of this :)

**Comment by fsciortino** [comment]
Yes, I've given up on uploading wheels (i.e. using `bdist_wheel`) because Aurora isn't a pure-python project and I was getting a headache from a million forums that give different indications on how to compile and upload wheels. So, using `python setup.py sdist` will do. 

The source distribution (.tar.gz file) seems to be built (and uploaded) correctly, but something doesn't work when I try to `pip install` from PyPI... I've tried to make sure that non-python files are added to any installation by modifying the `setup.py`, but with little luck. 

Let me know if you can make any progress! Thank you!

**Pull request merged**
