### PR TITLE
Modifications to atomic.py

### PR DESCRIPTION
**Pull request by fsciortino**
Updates to atomic.py to address issue #40 .

### CODE REVIEW

**Review by zli11 — APPROVED** [review]
Thanks for the changes and comments. It's much more clear to me now!

**Comment by fsciortino** [comment]
@zli11 hopefully this is going in the direction of addressing all your questions!

@odstrcilt I made a quick attempt at catching the cases where the ADAS grids are not exactly equally spaced (e.g. 96 acd/scd files for He). It's actually not entirely clear to me how bad CartesianGrid should perform in these cases. I'm skeptical that rewriting linear interpolation in fortran could be faster than the numpy alternatives, so I'm not going to put time into writing that code yet... Could you please have a look?

**Comment by zli11** [comment]
> @zli11 hopefully this is going in the direction of addressing all your questions!
> 
> @odstrcilt I made a quick attempt at catching the cases where the ADAS grids are not exactly equally spaced (e.g. 96 acd/scd files for He). It's actually not entirely clear to me how bad CartesianGrid should perform in these cases. I'm skeptical that rewriting linear interpolation in fortran could be faster than the numpy alternatives, so I'm not going to put time into writing that code yet... Could you please have a look?

Thanks for the so quick response and most of my concerns are solved!
BTW, for this equally spaced problem, I checked with ne=5e12 and Te=2e1, the difference compared to the table is at ~1-5% (_[[25146.64230869  1003.85272985]]_ vs _[[26159.66888482   995.81582847]]_). Still a number we can stand. :)

Cheers,
Zhi

**Comment by fsciortino** [comment]
thanks for checking those numbers, @zli11 ! Glad to hear that this helped :)

**Comment by fsciortino** [comment]
The reason why the automated tests were not passing was a cython bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1895315
Changing temporarily the testing to occur in python3.9 only has eliminated the problem.

**Comment by fsciortino** [comment]
Combined with PR #37, this PR should address all the raised points/questions. Thanks @zli11 for getting in touch!

**Pull request merged**
